version: "3.3"

services:
  mongo:
    image: mongo:4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=moleculer
      - POSTGRES_DB=mol-demo

volumes:
  mongo_data:
  pg_data:
